default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: gol-development

test:
  <<: *default
  database: gol-test

production:
  <<: *default
  encoding: unicode
  database: gol-production
